# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1583816fe5a00dd8695765881662fb2277234c6e93ec3e549d692cae7fe5bdbf8b386afc35c6bef3009ec5042c2986eb7689eafcc7864d273416c03e41eda821

test:
  secret_key_base: 4a33e94dcbe60acba3c65747e0653e9b7b2480cb22e80085f8b57e4fec561e429d705f1ce4b135ac7ea4da9782a4625f3511c9db1d4faae42a927050054febb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
